/*
 * generated by Xtext
 */
package com.emftriple.query.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class SparqlFormatter extends AbstractDeclarativeFormatter {

	@Override
	protected void configureFormatting(FormattingConfig c) {
		com.emftriple.query.services.SparqlGrammarAccess grammarAccess = 
			(com.emftriple.query.services.SparqlGrammarAccess) getGrammarAccess();

		c.setAutoLinewrap(400);
		// GroupGraphPattern
		c.setLinewrap(1).after( grammarAccess.getGroupGraphPatternSubAccess().getLeftCurlyBracketKeyword_0() );
		c.setIndentation( grammarAccess.getGroupGraphPatternSubAccess().getLeftCurlyBracketKeyword_0(), 
				grammarAccess.getGroupGraphPatternSubAccess().getRightCurlyBracketKeyword_4() );

		c.setLinewrap(1).after( grammarAccess.getGroupGraphPatternSubAccess().getFullStopKeyword_2_0() );
		c.setLinewrap(1).before( grammarAccess.getGroupGraphPatternSubAccess().getRightCurlyBracketKeyword_4() );

		//TriplesSameSubject
		c.setLinewrap().after(grammarAccess.getTriplesSameSubjectAccess().getSemicolonKeyword_2_0());
		c.setLinewrap().after(grammarAccess.getPropertyListAccess().getObjectAssignment_1());

		c.setNoSpace().between(
				grammarAccess.getUnNamedVariableAccess().getQuestionMarkKeyword_0(), 
				grammarAccess.getUnNamedVariableAccess().getNameAssignment_1()
		);
		c.setNoSpace().between(
				grammarAccess.getParameterAccess().getQuestionMarkColonKeyword_0(), 
				grammarAccess.getParameterAccess().getNameAssignment_1()
		);
//		c.setNoSpace().after(grammarAccess.getIRIAccess().getLessThanSignKeyword_1());
//		c.setNoSpace().before(grammarAccess.getIRIAccess().getGreaterThanSignKeyword_3());

		c.setLinewrap(2).after(grammarAccess.getConstructQueryAccess().getWhereClauseWhereClauseParserRuleCall_5_0());

	}
}
