/*
 * generated by Xtext
 */
package com.emftriple.query;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MQueryRuntimeModule extends com.emftriple.query.AbstractMQueryRuntimeModule {

}
