/*
 * generated by Xtext
 */
package com.emftriple.query;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JpqlRuntimeModule extends com.emftriple.query.AbstractJpqlRuntimeModule {

}
