/*
 * generated by Xtext
 */
package com.emftriple.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JpqlUiModule extends com.emftriple.query.ui.AbstractJpqlUiModule {
	public JpqlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
