/*
* generated by Xtext
*/
package com.emftriple.query.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MQueryAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/emftriple/query/parser/antlr/internal/InternalMQuery.tokens");
	}
}
