/*
* generated by Xtext
*/
package com.emftriple.query.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SparqlTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
