
/*
 * generated by Xtext
 */
 
package com.emftriple.query.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MQueryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.emftriple.query.ui.internal.MQueryActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.emftriple.query.ui.internal.MQueryActivator.getInstance().getInjector("com.emftriple.query.MQuery");
	}
	
}
