/*
 * generated by Xtext
 */
package com.emftriple.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SparqlUiModule extends com.emftriple.query.ui.AbstractSparqlUiModule {
	public SparqlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
