/*
 * generated by Xtext
 */
package com.emftriple.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MQueryUiModule extends com.emftriple.query.ui.AbstractMQueryUiModule {
	public MQueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
