/*
* generated by Xtext
*/
package com.emftriple.query.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MQueryProposalProvider extends AbstractMQueryProposalProvider {

}
